"""Correzione nome tabella

Revision ID: 21e6179814f1
Revises: 326a31fab62f
Create Date: 2024-11-10 20:46:46.658680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e6179814f1'
down_revision = '326a31fab62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_with_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('exercise_type', sa.String(length=100), nullable=False),
    sa.Column('description_it', sa.String(length=200), nullable=False),
    sa.Column('description_en', sa.String(length=200), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercise_whit_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_whit_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=200), nullable=False),
    sa.Column('exercise_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description_it', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description_en', sa.VARCHAR(length=200), nullable=False),
    sa.Column('upload_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercise_with_image')
    # ### end Alembic commands ###
