"""Aggiunta di ExerciseType e interazione con ExerciseWithImage

Revision ID: 953974bc720f
Revises: 21e6179814f1
Create Date: 2024-11-12 10:22:56.043254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953974bc720f'
down_revision = '21e6179814f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exerciseType', sa.String(length=100), nullable=False),
    sa.Column('exerciseWithImage', sa.Boolean(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_with_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_exercise_with_image_exercise_type',  # Nome esplicito del vincolo
            'exercise_type',  # Tabella referenziata
            ['exercise_type_id'],  # Colonna nella tabella corrente
            ['id']  # Colonna nella tabella referenziata
        )
        batch_op.drop_column('exercise_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_with_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_type', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exercise_type_id')

    op.drop_table('exercise_type')
    # ### end Alembic commands ###
